from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.schemas.recipe import RecipeGenerateRequest
from app.services.recipe_service import (
    save_recipe,
    get_recipe_by_id,
    get_all_recipes,
)

router = APIRouter(
    prefix="/recipes",
    tags=["Recipes"],
)


@router.post("/generate")
def generate_recipe(
    request: RecipeGenerateRequest,
    db: Session = Depends(get_db),
):
    # Dummy recipe for now
    recipe = save_recipe(
        db=db,
        title="Sample Recipe",
        ingredients=", ".join(request.ingredients),
        instructions="This recipe will be generated by Gemini later.",
        cooking_time=30,
        servings=request.servings or 2,
        user_id=1,
    )

    return recipe


@router.get("/")
def list_recipes(db: Session = Depends(get_db)):
    return get_all_recipes(db)


@router.get("/{recipe_id}")
def get_recipe(recipe_id: int, db: Session = Depends(get_db)):
    recipe = get_recipe_by_id(db, recipe_id)

    if not recipe:
        raise HTTPException(
            status_code=404,
            detail="Recipe not found",
        )

    return recipe
